### ISSUE TITLE
Missing stack trace since version 1.49.2

### ISSUE THREAD

**Issue by kailip** [epsagon/epsagon-python#275]
Hello. We're using epsagon-python in Django project with gunicorn server (worker_class = "gevent"). Since version 1.49.2, our Slack notifications aren't working as expected. Instead of actual error, we can see only "Error detected" message. I tried it locally with debug option set to True, and I can see, that in version 1.49.1 there was an exception object (with type, message, traceback and so on) inside an event object in trace being sent. In version 1.49.2 and newer, there is no "exception" key in that object.

**Comment by ranrib** [comment]
Thanks @kailip - do you mind sharing how are you raising exceptions in general? Is it just an unhandled exception in the route/view?

**Comment by kailip** [comment]
It was an unhandled exception, tested with returning `None/1` in view.

**Comment by kailip** [comment]
Thank you! Testes in version 1.53.0, works like a charm.
