### ISSUE TITLE
Just need some info about communication from your service to our infra

### ISSUE THREAD

**Issue by mayur741** [epsagon/epsagon-python#279]
Hi, this is not really a issue, I just needed more info on communication from your service to our serverless infra.
I tried asking in help widget  but didn't get any reply.
We really liked this service and want to integrate it to monitor our serverless architecture,but our security team raised few questions over communication between your server and our infra.
We are bit confused about how do you send any updates made in dashboard to reflect in our infra, is it via cloudformation custom resource (SNS in this case)?

Thank you.
Sorry for raising this in an inappropriate place.

**Comment by ranrib** [comment]
Hi @mayur741 - sorry for missing this out. I'm sending you a reply now through the email. Thanks!
