### ISSUE TITLE
tracing not working with celery worker

### ISSUE THREAD

**Issue by matthieudesprez** [epsagon/epsagon-python#345]
I didn't get the time to dig too far but I can't have epsagon traces with celery.

From what I've seen, the _get_trace function returns None, as the unique_id is None and the singleton_trace is also None.

I'm running celery with the following command:
```
celery -A <app_name> worker --beat --scheduler django
```

and I tried both the auto tracing config and calling epsagon.init directly, but the outcome is the same.

**Comment by ranrib** [comment]
Hi @matthieudesprez, can you share celery version and example snippet?
also can you set EPSAGON_DEBUG=TRUE logs?
