### ISSUE TITLE
Dependency update

### ISSUE THREAD

**Issue by GreenSmile** [epsagon/epsagon-python#50]
Hi guys, 

While trying to install epsagon I faced issue with couple outdated dependencies:
```
epsagon 1.0.46 has requirement future==0.16.0, but you'll have future 0.17.1 which is incompatible.
epsagon 1.0.46 has requirement six==1.11.0, but you'll have six 1.12.0 which is incompatible.
```
It causes dependency conflict with other packages in my project.

Could you please update requirements if it is possible?

**Comment by ranrib** [comment]
Hi @GreenSmile, definitely - we will make sure it works correctly and update it accordingly.
